changelog:
  exclude:
    labels:
      - ignore-for-release
      - release
  categories:
    - title: Breaking changes
      labels:
        - Semver-Major
        - breaking-change
    - title: Features
      labels:
        - Semver-Minor
        - enhancement
        - feature
    - title: Fixes and maintenance
      labels:
        - "*"
